name: Build Web

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Store variables
        run: |
          touch .env
          echo 'VITE_APP_GITHUB_BASE=/epub-reader' >> .env

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: deploy web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
